# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 13:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='offering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=45)),
                ('receipt_code', models.CharField(max_length=45, unique=True)),
                ('tithes', models.IntegerField()),
                ('combinedoffering', models.IntegerField()),
                ('campmeetingoffering', models.IntegerField()),
                ('churchbuilding', models.IntegerField()),
                ('conference', models.IntegerField()),
                ('localchurch', models.IntegerField()),
                ('funds', models.IntegerField()),
                ('total', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('member_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='offering',
            unique_together=set([('receipt_code',)]),
        ),
    ]
